---
global:
  scrape_interval: '5s'

rule_files:
  - "alerts.yml"

    #alerting:
    #  alertmanagers:
    #  - scheme: http
    #    static_configs:
    #    - targets:
    #      - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "192.168.1.254:42007"

  - job_name: "postgres-exporter"
    static_configs:
      - targets:
        - "192.168.1.254:42008"

# can be checked via: 
# https://prometheus.dea/targets?search=
