version: "3.7"
services:
    etcd-3:
        image: quay.io/coreos/etcd:v3.5.16
        restart: unless-stopped
        entrypoint: /usr/local/bin/etcd
        ports:
            - 2379:2379
            - 2380:2380
        command:
            - '--name=etcd-3'
            - '--initial-advertise-peer-urls=http://172.17.210.19:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://172.17.210.19:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://172.17.210.17:2380,etcd-2=http://172.17.210.18:2380,etcd-3=http://172.17.210.19:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=mys3cr3ttok3n'
            - '--data-dir=/etcd-data'
        volumes:
            - ./etcd:/etcd-data

