version: "3.7"

services:

  postgres:
    image: postgres:15.10
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "otus"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otus -d otus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
