---
global:
  scrape_interval: '5s'

rule_files:
  - "alerts.yml"

    #alerting:
    #  alertmanagers:
    #  - scheme: http
    #    static_configs:
    #    - targets:
    #      - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "172.17.210.7:9090"

  - job_name: "monitoring"
    static_configs:
      - targets:
        - "172.17.210.7:9100"

  - job_name: "postgres-patroni-master"
    static_configs:
      - targets:
        - "172.17.210.7:9187"

  - job_name: "patroni"
    metrics_path: /metrics
    static_configs:
      - targets:
        - "172.17.210.17:8008"
        - "172.17.210.18:8008"
        - "172.17.210.19:8008"

  - job_name: "etcd"
    metrics_path: /metrics
    static_configs:
      - targets:
        - "172.17.210.17:2379"
        - "172.17.210.18:2379"
        - "172.17.210.19:2379"

  - job_name: "haproxy"
    metrics_path: /metrics
    static_configs:
      - targets:
        - "172.17.210.20:9101"

# can be checked via: 
# https://172.17.210.7/targets?search=
